export const LIST_POPULER_PRODUCTS = [
    {
        id: 1,
        name: "Beras Putih Premium Grade A",
        image: "/category2.jpg",
        price: 12500,
        unit: "per Kg",
        sold: 620,
        store: "Kios Beras Makmur",
        location: "Grobogan, Jawa Tengah",
        badge: "Populer",
    },
    {
        id: 2,
        name: "Beras Merah Organik Super",
        image: "/category2.jpg",
        price: 18500,
        unit: "per Kg",
        sold: 210,
        store: "Sentra Padi Nusantara",
        location: "Pati, Jawa Tengah",
        badge: "Unggulan",
    },
    {
        id: 3,
        name: "Beras Pandan Wangi Lokal",
        image: "/category2.jpg",
        price: 14500,
        unit: "per Kg",
        sold: 480,
        store: "Beras Subur Abadi",
        location: "Blora, Jawa Tengah",
        badge: "Populer",
    },
    {
        id: 4,
        name: "Beras Coklat Premium",
        image: "/category2.jpg",
        price: 16500,
        unit: "per Kg",
        sold: 310,
        store: "Toko Hasil Panen Sejahtera",
        location: "Demak, Jawa Tengah",
        badge: "Populer",
    },
    {
        id: 5,
        name: "Beras Hitam Organik",
        image: "/category2.jpg",
        price: 22000,
        unit: "per Kg",
        sold: 175,
        store: "Kios Petani Berkah",
        location: "Kudus, Jawa Tengah",
        badge: "Unggulan",
    },
];