export const LIST_FOR_YOU = [
    {
        id: 1,
        name: "Beras Putih Premium Grade A",
        slugProduct: "beras-putih-premium-grade-a",
        image: "/category2.jpg",
        price: 12500,
        unit: "per Kg",
        store: "Kios Beras Makmur",
        slugStore: "kios-beras-makmur",
        location: "Kudus, Jawa Tengah",
        sold: 520
    },
    {
        id: 2,
        name: "Beras Merah Organik Super",
        slugProduct: "beras-merah-organik-super",
        image: "/category2.jpg",
        price: 18500,
        unit: "per Kg",
        store: "Sentra Padi Nusantara",
        slugStore: "sentra-padi-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 160
    },
    {
        id: 3,
        name: "Beras Pandan Wangi Lokal",
        slugProduct: "beras-pandan-wangi-lokal",
        image: "/category2.jpg",
        price: 14500,
        unit: "per Kg",
        store: "Beras Subur Abadi",
        slugStore: "beras-subur-abadi",
        location: "Sleman, Yogyakarta",
        sold: 680
    },
    {
        id: 4,
        name: "Beras Coklat Premium",
        slugProduct: "beras-coklat-premium",
        image: "/category2.jpg",
        price: 16500,
        unit: "per Kg",
        store: "Toko Hasil Panen Sejahtera",
        slugStore: "toko-hasil-panen-sejahtera",
        location: "Blitar, Jawa Timur",
        sold: 410
    },
    {
        id: 5,
        name: "Beras Hitam Organik",
        slugProduct: "beras-hitam-organik",
        image: "/category2.jpg",
        price: 22000,
        unit: "per Kg",
        store: "Kios Petani Berkah",
        slugStore: "kios-petani-berkah",
        location: "Boyolali, Jawa Tengah",
        sold: 190
    },
    {
        id: 6,
        name: "Beras Basmati Import Premium",
        slugProduct: "beras-basmati-import-premium",
        image: "/category2.jpg",
        price: 45000,
        unit: "per Kg",
        store: "Sentra Padi Nusantara",
        slugStore: "sentra-padi-nusantara",
        location: "Jakarta Barat, DKI Jakarta",
        sold: 95
    },
    {
        id: 7,
        name: "Beras Rojolele Super",
        slugProduct: "beras-rojolele-super",
        image: "/category2.jpg",
        price: 16000,
        unit: "per Kg",
        store: "Beras Tani Subur",
        slugStore: "beras-tani-subur",
        location: "Ngawi, Jawa Timur",
        sold: 430
    },
    {
        id: 8,
        name: "Beras IR 64 Lokal Grobogan",
        slugProduct: "beras-ir64-lokal-grobogan",
        image: "/category2.jpg",
        price: 11800,
        unit: "per Kg",
        store: "Kios Beras Jaya",
        slugStore: "kios-beras-jaya",
        location: "Grobogan, Jawa Tengah",
        sold: 720
    },
    {
        id: 9,
        name: "Beras Jasmine Import",
        slugProduct: "beras-jasmine-import",
        image: "/category2.jpg",
        price: 38000,
        unit: "per Kg",
        store: "Toko Petani Mandiri",
        slugStore: "toko-petani-mandiri",
        location: "Surabaya, Jawa Timur",
        sold: 120
    },
    {
        id: 10,
        name: "Beras Merah Lokal Klaten",
        slugProduct: "beras-merah-lokal-klaten",
        image: "/category2.jpg",
        price: 17000,
        unit: "per Kg",
        store: "Kios Beras Berkah",
        slugStore: "kios-beras-berkah",
        location: "Klaten, Jawa Tengah",
        sold: 210
    },
    {
        id: 11,
        name: "Beras Putih Medium IR42",
        slugProduct: "beras-putih-medium-ir42",
        image: "/category2.jpg",
        price: 11200,
        unit: "per Kg",
        store: "Sentra Padi Nusantara",
        slugStore: "sentra-padi-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 640
    },
    {
        id: 12,
        name: "Beras Hitam Premium Sleman",
        slugProduct: "beras-hitam-premium-sleman",
        image: "/category2.jpg",
        price: 25000,
        unit: "per Kg",
        store: "Toko Tani Sejahtera",
        slugStore: "toko-tani-sejahtera",
        location: "Sleman, Yogyakarta",
        sold: 150
    },
    {
        id: 13,
        name: "Beras Pandan Wangi Premium",
        slugProduct: "beras-pandan-wangi-premium",
        image: "/category2.jpg",
        price: 15500,
        unit: "per Kg",
        store: "Beras Subur Abadi",
        slugStore: "beras-subur-abadi",
        location: "Sukoharjo, Jawa Tengah",
        sold: 480
    },
    {
        id: 14,
        name: "Beras Rojolele Klaten Asli",
        slugProduct: "beras-rojolele-klaten-asli",
        image: "/category2.jpg",
        price: 17500,
        unit: "per Kg",
        store: "Kios Petani Mandiri",
        slugStore: "kios-petani-mandiri",
        location: "Klaten, Jawa Tengah",
        sold: 370
    },
    {
        id: 15,
        name: "Beras Premium Export Quality",
        slugProduct: "beras-premium-export-quality",
        image: "/category2.jpg",
        price: 18500,
        unit: "per Kg",
        store: "Toko Beras Nusantara",
        slugStore: "toko-beras-nusantara",
        location: "Demak, Jawa Tengah",
        sold: 290
    },
    {
        id: 16,
        name: "Beras Putih Medium Pati",
        slugProduct: "beras-putih-medium-pati",
        image: "/category2.jpg",
        price: 11000,
        unit: "per Kg",
        store: "Kios Pangan Rakyat",
        slugStore: "kios-pangan-rakyat",
        location: "Pati, Jawa Tengah",
        sold: 500
    },
    {
        id: 17,
        name: "Beras Merah Organik Boyolali",
        slugProduct: "beras-merah-organik-boyolali",
        image: "/category2.jpg",
        price: 18500,
        unit: "per Kg",
        store: "Toko Tani Berkah",
        slugStore: "toko-tani-berkah",
        location: "Boyolali, Jawa Tengah",
        sold: 145
    },
    {
        id: 18,
        name: "Beras Cianjur Super",
        slugProduct: "beras-cianjur-super",
        image: "/category2.jpg",
        price: 15000,
        unit: "per Kg",
        store: "Kios Beras Lestari",
        slugStore: "kios-beras-lestari",
        location: "Cianjur, Jawa Barat",
        sold: 610
    },
    {
        id: 19,
        name: "Beras Jepang (Short Grain)",
        slugProduct: "beras-jepang-short-grain",
        image: "/category2.jpg",
        price: 42000,
        unit: "per Kg",
        store: "Toko Pangan Mandiri",
        slugStore: "toko-pangan-mandiri",
        location: "Jakarta Pusat, DKI Jakarta",
        sold: 85
    },
    {
        id: 20,
        name: "Beras Mentik Wangi Premium",
        slugProduct: "beras-mentik-wangi-premium",
        image: "/category2.jpg",
        price: 16500,
        unit: "per Kg",
        store: "Beras Tani Subur",
        slugStore: "beras-tani-subur",
        location: "Ngawi, Jawa Timur",
        sold: 390
    },
    {
        id: 21,
        name: "Beras Putih Lokal Pati",
        slugProduct: "beras-putih-lokal-pati",
        image: "/category2.jpg",
        price: 11200,
        unit: "per Kg",
        store: "Kios Beras Pati",
        slugStore: "kios-beras-pati",
        location: "Pati, Jawa Tengah",
        sold: 450
    },
    {
        id: 22,
        name: "Beras Hitam Grade Premium",
        slugProduct: "beras-hitam-grade-premium",
        image: "/category2.jpg",
        price: 26000,
        unit: "per Kg",
        store: "Toko Hasil Panen",
        slugStore: "toko-hasil-panen",
        location: "Blitar, Jawa Timur",
        sold: 130
    },
    {
        id: 23,
        name: "Beras Medium IR64 Jawa Timur",
        slugProduct: "beras-medium-ir64-jawa-timur",
        image: "/category2.jpg",
        price: 11500,
        unit: "per Kg",
        store: "Kios Petani Jaya",
        slugStore: "kios-petani-jaya",
        location: "Magetan, Jawa Timur",
        sold: 700
    },
    {
        id: 24,
        name: "Beras Jasmine Import Premium",
        slugProduct: "beras-jasmine-import-premium",
        image: "/category2.jpg",
        price: 39000,
        unit: "per Kg",
        store: "Sentra Padi Nusantara",
        slugStore: "sentra-padi-nusantara",
        location: "Jakarta Timur, DKI Jakarta",
        sold: 60
    },
    {
        id: 25,
        name: "Beras Pandan Wangi Premium Blora",
        slugProduct: "beras-pandan-wangi-premium-blora",
        image: "/category2.jpg",
        price: 15800,
        unit: "per Kg",
        store: "Beras Subur Nusantara",
        slugStore: "beras-subur-nusantara",
        location: "Blora, Jawa Tengah",
        sold: 310
    },
    {
        id: 26,
        name: "Beras Putih Super Demak",
        slugProduct: "beras-putih-super-demak",
        image: "/category2.jpg",
        price: 12000,
        unit: "per Kg",
        store: "Toko Beras Mandiri",
        slugStore: "toko-beras-mandiri",
        location: "Demak, Jawa Tengah",
        sold: 480
    },
    {
        id: 27,
        name: "Beras Medium Pati Konsumsi",
        slugProduct: "beras-medium-pati-konsumsi",
        image: "/category2.jpg",
        price: 11300,
        unit: "per Kg",
        store: "Kios Pangan Nusantara",
        slugStore: "kios-pangan-nusantara",
        location: "Pati, Jawa Tengah",
        sold: 410
    },
    {
        id: 28,
        name: "Beras Premium Export Quality Jawa",
        slugProduct: "beras-premium-export-quality-jawa",
        image: "/category2.jpg",
        price: 19000,
        unit: "per Kg",
        store: "Beras Lestari Mandiri",
        slugStore: "beras-lestari-mandiri",
        location: "Bojonegoro, Jawa Timur",
        sold: 175
    },
    {
        id: 29,
        name: "Beras Mentik Wangi Unggul Pati",
        slugProduct: "beras-mentik-wangi-unggul-pati",
        image: "/category2.jpg",
        price: 17000,
        unit: "per Kg",
        store: "Toko Tani Sejahtera",
        slugStore: "toko-tani-sejahtera",
        location: "Pati, Jawa Tengah",
        sold: 95
    },
    {
        id: 30,
        name: "Beras IR64 Pilihan Grobogan",
        slugProduct: "beras-ir64-pilihan-grobogan",
        image: "/category2.jpg",
        price: 11600,
        unit: "per Kg",
        store: "Kios Beras Nusantara",
        slugStore: "kios-beras-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 690
    }
]